#!/bin/sh

# This tells you what's changed between two Koji tags.
# It's remarkable skimpy on error checking. 
# Common usage:
# 
#    koji-tag-diff el5-osg-testing el5-osg-release

if [ $# -ne 2 ]; then
    echo "Usage: koji-tag-diff <tag1> <tag2>"
    exit 1
fi

tag1=$1
tag2=$2

file1=`mktemp -t koji-$tag1-XXXXXX`
file2=`mktemp -t koji-$tag2-XXXXXX`

echo "Comparing '$tag1' to '$tag2'"

koji list-tagged --latest $tag1 | awk '{print $1}' > $file1
koji list-tagged --latest $tag2 | awk '{print $1}' > $file2

diff -u $file1 $file2 | grep -v -- "---" | grep  '^\-' | cut -b 2-

rm -f $file1 $file2
