#!/usr/bin/env python2
import logging
import sys
from osgbuild import error
from osgbuild import promoter

log = logging.getLogger('')
log.setLevel(logging.INFO)
log_consolehandler = logging.StreamHandler()
log_consolehandler.setLevel(logging.INFO)
log_formatter = logging.Formatter("%(message)s")
log_consolehandler.setFormatter(log_formatter)
log.addHandler(log_consolehandler)

if __name__ == "__main__":
    try:
        sys.exit(promoter.main(sys.argv))
    except error.Error, e:
        print >>sys.stderr, e
        sys.exit(1)

