#!/usr/bin/env python
"Load and run the main osg-build script"
# pylint: disable=C0103
import os
import sys
import logging
import traceback

from osgbuild import main
from osgbuild.error import Error, UsageError


try:
    sys.exit(main.main(sys.argv))
except UsageError, err:
    print >> sys.stderr, str(err)
    print >> sys.stderr, "Type '" + sys.argv[0] + " --help' for usage info."
    sys.exit(2)
except SystemExit, err:
    raise
except KeyboardInterrupt:
    print >> sys.stderr, ""
    print >> sys.stderr, "-" * 79
    print >> sys.stderr, "Interrupted"
    print >> sys.stderr, "-" * 79
    sys.exit(3)
except Error, err:
    print >> sys.stderr, "-" * 79
    print >> sys.stderr, str(err)
    print >> sys.stderr, "-" * 79
    logging.debug("Full traceback follows:")
    logging.debug(err.traceback)
    sys.exit(4)
except Exception, err:
    print >> sys.stderr, "-" * 79
    print >> sys.stderr, "An exception occurred:"
    print >> sys.stderr, str(err)
    print >> sys.stderr, "-" * 79
    print >> sys.stderr, "Full traceback follows:"
    traceback.print_exc()
    sys.exit(1)
