#!/bin/bash
# A quick and dirty script to give us a list of packages that are tagged as
# both el5 and el6 in koji.

el6tags=`koji list-tags | egrep '\bel6\b'`
for tag in $el6tags; do
    echo looking in tag $tag
    for build in `koji -q list-tagged $tag | awk '{print $1}'`; do
        badtags=`koji buildinfo $build | grep Tags | egrep '\bel5\b'`
        if [[ -n $badtags ]]; then
            echo $build has bad tags: $badtags
        fi
    done
done

